const constants = {
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  CREATE_USER: 'CREATE_USER',
  LOGIN_USER: 'LOGIN_USER',
  GET_STUDENT_STATUS: 'GET_STUDENT_STATUS',
  LOGOUT_USER: 'LOGOUT_USER',
  UPDATE_PROGRESS: 'UPDATE_PROGRESS',
  ADD_USER_IMAGE: 'ADD_USER_IMAGE',
  EDIT_USER: 'EDIT_USER',
  EDIT_PHOTO: 'EDIT_PHOTO',
  SET_HIGHEST_SCORE: 'SET_HIGHEST_SCORE',
  SET_MERN_HIGHEST_SCORE: 'SET_MERN_HIGHEST_SCORE',
};
export default constants;
